root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./cmd/api"
bin = "./tmp/app"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules"]
args_bin = ["dev", "--port", "8080"]
delay = 1000
kill_delay = 500
send_interrupt = true
stop_on_error = true
log = "air.log"